### ISSUE TITLE
Migrate gradle-script-kotlin build scripts

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#169]

**Comment by eskatos** [comment]
Yay! No more `build.gradle` file to build `gradle-script-kotlin`.
Checked and everything works as expected.

However, in IDEA I get some errors in the editor.

This ones looks like IDEA is misunderstanding the scope of `this`:
![image](https://cloud.githubusercontent.com/assets/132773/19969542/4dc1e7aa-a1d9-11e6-8f45-d0092eb9882d.png)

The other one will be fixed by #125:
![image](https://cloud.githubusercontent.com/assets/132773/19969342/7fb684b0-a1d8-11e6-8bb0-e9a8d4a6f33e.png)

Other than that it LGTM, closing.
