### ISSUE TITLE
Setting non-existent Kotlin build script in settings.gradle should not fail

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle-script-kotlin#302]
Setting non-existent build script file with `.kts` extension results in `settings.gradle` like:

`rootProject.buildFileName = 'build.non-existent.kts'`

results in build failing with:

`kotlin.KotlinNullPointerException (no error message)`

It should not fail as build scripts are optional.

**Comment by eskatos** [comment]
If the file doesn't exists, Gradle provides a `NonExistentFileScriptSource`.
The Groovy provider compiles the text provided by this `ScriptSource`, which is `""`.
The Kotlin provider works with `scriptSource.resource.file` which is `null` in this case, causing the NPE.

**Comment by bamboo** [comment]
I think there are two different use cases here:

 1. For a project, the default build script (automatically detected or defined in `settings.gradle`) is optional and so we shouldn't throw if the file isn't there
 2. For a script plugin, e.g. `apply from: "someScript.gradle.kts"`, we should throw if the file isn't there

That reasoning tells me we shouldn't be fixing _1_ at the script plugin factory level but at a higher-level.

**Comment by eskatos** [comment]
The Gradle runtime already distinguishes the various use cases and fails with a proper error message when it has to.

A scripting provider may decide to add stuff to build scripts, e.g. base plugins like we envision in order to solve #320. Even when the file isn't there because it is optional.

So, I think this boils down to the contracts of `NonExistentFileScriptSource` and it's companion `EmptyFileTextResource` being loosely defined.

**Comment by eskatos** [comment]
When it comes to the settings scripts there actually are three cases:
1. specified settings script file exists
2. specified settings script file does not exists
3. using empty settings, there's no `File` involved, see `SettingsLocation` and `BuildLayout` in GBT

In the 1st case the `ScriptSource` passed to the `ScriptPluginFactory` is a `UriScriptSource`, already properly handled.

In the 2nd case it is a `NonExistentFileScriptSource` whose `TextResource` returns a `null` `File`. We need to accommodate here.

In the 3rd case the `ScriptSource` passed to the `ScriptPluginFactory` is a `StringScriptSource` that use its class name as `fileName`. In that case we can't distinguish the "file" path and name.

So, the `KotlinScriptPluginFactory` must not use the nullable `file` property of the `ScriptSource#resource` in order to handle all those cases while letting the Gradle runtime make the decisions wrt. optional scripts and eventual failures.

**Comment by bamboo** [comment]
About case _3_, why should Gradle even call the _ScriptPluginFactory_?

**Comment by bamboo** [comment]
With regards to my question above, I clarify: why should Gradle even call the `ScriptPluginFactory` to compile an empty _Settings_ plugin?

**Comment by eskatos** [comment]
@bamboo it's calling the `ScriptPluginFactory` with an "empty text" `ScriptSource` to give it a chance to eventually enhance it. See my https://github.com/gradle/gradle-script-kotlin/issues/302#issuecomment-293629148 above

**Comment by bamboo** [comment]
Ok. I guess it makes sense to treat all plugin targets homogeneously in that regard.
