### ISSUE TITLE
Cache compiled build scripts

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#31]
- [x] @ligee to get back regarding how to control the location of compiled `.kts` scripts

**Comment by cbeams** [comment]
@ligee, I've assigned this issue to you, as we're waiting on info about the location of compiled `.kts` scripts. Just let us know and I'll assign it back to one of us to take the next steps.

**Comment by cbeams** [comment]
Slating this for M3 to ensure we get the most important features implemented by the M2 deadline. Note that while script caching will improve performance, it is less important in the context of the daemon being enabled by default.

**Comment by cbeams** [comment]
This is what we'll need to add to our compiler configuration to enable script caching

```
configuration.put(JVMConfigurationKeys.RETAIN_OUTPUT_IN_MEMORY, true)
configuration.put(JVMConfigurationKeys.OUTPUT_DIRECTORY, saveClassesDir)
```

**Comment by melix** [comment]
Copied from Slack:

Cédric> does it make sure it works properly cross-process? That is to say, uses the same guards/cache managers as the Groovy version?

[08:52]  
There were quite a few bugs in the past wrt the Groovy scripts, for example 2 process using the same script file, but one is changed during the execution of the other. Using a simple directory for output doesn't work for this.

[08:53]  
(that's why the caching strategy in `FileCacheBackedScriptClassCompiler` is complex (not speaking of the L1 in-memory cache)
