### ISSUE TITLE
Shouldn't a change in a kts build file trigger a rebuild?

### ISSUE THREAD

**Issue by kohlerm** [gradle/gradle-script-kotlin#352]
When I change the version number in the samples/copy project build file the files don't get re-compiled, but I guess they should be. 
Is this a missing feature or a bug?

**Comment by bamboo** [comment]
Hi, @kohlerm.

A change in the build script by itself won't invalidate the results of previous builds. Changes in task dependencies will.

The behaviour you notice is due to `Copy#filter` properties not being considered as inputs to the task by default. 

To get the behaviour you expect, the dependency must be explicitly declared as in e6422350130ad24c0ba263795be06f0f6ce68317.

Does that answer your question?

**Comment by eskatos** [comment]
FTR the upstream issue is https://github.com/gradle/gradle/issues/1191
